name: Deploy version

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Which tag you want to deploy? (e.g. 1.2.3)
      environment:
        type: choice
        required: true
        default: 'dev' 
        description: To which environment you want to deploy?
        options: 
        - dev
        - prod

env:
  PROJECT_NAME: node-express-kubernetes-example
  ORGANIZATION: juffalow

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'prod'
    steps:
    - uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Obtain kubernetes config
      env:
        cluster: ${{ secrets.DIGITALOCEAN_KUBERNETES_PRODUCTION }}
      run: doctl kubernetes cluster kubeconfig save $cluster
    - name: Set version
      id: version
      run: echo ::set-output name=tag::${{ github.event.inputs.tag }}
    - name: Deploy new version
      env:
        VERSION: ${{ steps.version.outputs.tag }}
      run: |
        kubectl set image deployment/$PROJECT_NAME-deployment $PROJECT_NAME-application=registry.digitalocean.com/$ORGANIZATION/$PROJECT_NAME:$VERSION
