name: github-actions-ecommerce

on: 
  push:
    branches:
      - master

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set image tag (first 4 chars of commit SHA)
      - name: Set image tag
        id: image_tag
        run: echo "tag=${GITHUB_SHA::4}" >> "$GITHUB_OUTPUT"

      # Login to Docker Hub
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PET }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Capital D if your Dockerfile is named like that
          push: true
          tags: |
                ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.image_tag.outputs.tag }}
                ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
